# Trading212 to GnuCash Multi-Split Converter Configuration
# Edit this file to customize your ticker symbols and account mappings

# Map Trading212 ticker symbols to Yahoo Finance symbols
ticker_map:
  ORA: ORAN.PA      # Orange SA
  VOD: VOD.L        # Vodafone Group PLC
  MSFT: MSFT        # Microsoft Corporation
  AAPL: AAPL        # Apple Inc.
  GOOGL: GOOGL      # Alphabet Inc.

# GnuCash accounts for fees and taxes
# Note: For share transactions, Transfer Account uses company name directly (e.g., "Microsoft Corporation")
# Note: Source account (where money comes from/goes to) is configured during GnuCash import
expense_accounts:
  conversion_fee: "Expenses:Currency Conversion Fees"
  french_tax: "Expenses:French Transaction Tax"

# Account for deposits from Trading212
deposit_account: "Assets:Trading212 Deposits"
